### ISSUE TITLE
error on categories (setting -> categories

### ISSUE THREAD

**Issue by hajir** [bsup1/akaunting#16]
تنظیمات صفحه بخش
http://hesabdari.bsup.tk/settings/categories

![image](https://user-images.githubusercontent.com/3663623/40590980-b8b56884-61bd-11e8-83e3-7def5b312084.png)

**Comment by hafez-bsup** [comment]
It seems to be a bug in akaunting itself:
https://github.com/akaunting/akaunting/issues/211

It has been resolved on their update but we can't update the app due to our customization. I'm working on it.
