### ISSUE TITLE
Getting error on contractor page

### ISSUE THREAD

**Issue by hajir** [bsup1/akaunting#5]
I tried to install the software by http://localhost/akaunting-master/install
After login, i clicked on the contractor page but got this error

![image](https://user-images.githubusercontent.com/3663623/38347357-da8e3d10-384f-11e8-96df-d9584143fc84.png)

**Comment by hafez-bsup** [comment]
Would you please copy `app/storage/log/laravel.log` file here?

**Comment by hajir** [comment]
[laravel.log](https://github.com/bsup1/akaunting/files/1885681/laravel.log)
