### ISSUE TITLE
New Report - درآمد و پرداخت های شخص

### ISSUE THREAD

**Issue by hajir** [bsup1/akaunting#8]
Create a new report under Reports section
![image](https://user-images.githubusercontent.com/3663623/37800520-42d31d16-2de0-11e8-80b1-f2cfbb337d7e.png)

**Structure**
The structure of the report is explained in the issue below. 

In this report, user can select 
+ a vendor from the dropdown. The report is generated for the selected person. All values is related for that person.
+ or "All Vendors - تمام اشخاص".

**Number Formating**
+The format of the numbers for Toman Values is like ۱،۰۰۰
+The format of dollar amounts is like 5.10

![image](https://user-images.githubusercontent.com/3663623/37801615-787a30cc-2de4-11e8-821c-58dd2b94fb2f.png)

**Comment by hajir** [comment]
English title: Income vs. Expenses 2
عنوان فارسی: درآمد و پرداخت های شخص

**Comment by hajir** [comment]
**Fields**

+ Revenue in Toman is the amount field in Income >> Revenue
+ Payment in Toman is the amount field in Expense >> Payments
+ Payment in CAD is the field explained in #7 
+ Category field: Each revenue or payment belongs to a category

**Comment by hafez-bsup** [comment]
1. Don't forget to add new permissions (or re-seed the permissions and role_permissions tables)
1. Don't forget to add 2 new currencies CAD and IRR (or Toman).
1. Don't forget to make IRR (or Toman) default currency.
```
INSERT INTO table_name (company_id, name, code, rate, enabled, precision, symbol, symbol_first, decimal_mark, thousands_separator)
VALUES (1, 'دلار کانادا', 'CAD', 1, 1, 2, '$', 1, '.', ',');

INSERT INTO table_name (company_id, name, code, rate, enabled, precision, symbol, symbol_first, decimal_mark, thousands_separator)
VALUES (1, 'ریال ایران', 'IRR', 1, 1, 0, 'ريال', 0, '/', ',');
```
